title: Thi

github: WVarduinoclub
discord-link: https://discord.gg/jMveTFx5https://discord.gg/jMveTFx5
# url: https://wvarduinoclub.github.io

# Jekyll has a bug! If it crashes, try making an change to the config file and trying again.